### ISSUE TITLE
"content" only shows "[object Object]"

### ISSUE THREAD

**Issue by gustavklopp** [agrinko/jquery-contenteditable#1]
Hi! Thanks for this very nice addon!
Unfortunately, I can't get it right...

`<div clas="test"> TEST IT</div>`
with in my `.js` file:
```
$(".test").editable({
	save:function(content) {
		alert(content);
```
It results in an alert with `[object Object]` inside.

**Comment by agrinko** [comment]
Hi @gustavklopp
Did you resolve the issue? What was the cause?

**Comment by gustavklopp** [comment]
Ooh I get it!
the `README` is not up-to-date!
it's : 
```
 save: function(e, ui) {
       alert("Saving actual content: " + ui.content);
```
 not
```
 save: function(content) {
        alert("Saving actual content: " + content);
```
The `README` needs an update.
